#!/bin/bash
# Author : Dilshan Wijesooriya (dilshanonline@gmail.com)
#GitHub : https://github.com/dilshanonline

path=`pwd` ; cd $path

#-- Definitions
RED='\033[0;31m'
BLUE='\033[0;34m'
D_GRAY='\033[1;30m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
ORANGE='\033[0;33m'
LGREEN='\033[1;32m'
NC='\033[0m'
sys_date=$(date)
u_name=$(whoami)

#-- Welcome Message
clear
echo -e "${RED}"
echo -e "                    _             __  __                                   ${RED}"
echo -e "                   (_)           |  \/  |                                  ${RED}"
echo -e "  ___  ___  ___ ___ _  ___  _ __ | \  / | __ _ _ __   __ _  __ _  ___ _ __ ${RED}"
echo -e " / __|/ _ \/ __/ __| |/ _ \|  _ \| |\/| |/ _  |  _ \ / _  |/ _  |/ _ \  __|${RED}"
echo -e " \__ \  __/\__ \__ \ | (_) | | | | |  | | (_| | | | | (_| | (_| |  __/ |   ${RED}"
echo -e " |___/\___||___/___/_|\___/|_| |_|_|  |_|\__,_|_| |_|\__,_|\__, |\___|_|   ${RED}"
echo -e "                           By Dilshan Wijesooriya           __/ |          ${RED}"
echo -e "                              Version : 1.1.3              |___/           ${RED}"
echo ""
echo -e "${ORANGE}System Time : ${GREEN}$sys_date"
echo -e "${ORANGE}System User : ${GREEN}$u_name"
echo ""
echo -e "${RED}Project List : "
echo ""

#-- Functions
#-- Read and printing projects.txt
function printprojectlist {

	while read line;
	do
		if [[ $line != \#* ]];
		then
			project_id=$(echo $line | cut -d' ' -f1)
			project=$(echo $line | cut -d' ' -f2)
			echo -e "\t${ORANGE}$project_id \t${GREEN}":  "$project"
		fi

	done < ./projects.txt;
}

#-- Read and printing serverlist.txt
function printserverlist {

	echo ""
	echo -e -n "${RED}Select a project:${NC} " ; read _project_id
	echo ""

	while read line;
	do
		if [[ $line != \#* ]];
		then
			project_id=$(echo $line | cut -d' ' -f1)
			if [[ $project_id -eq $_project_id ]];
			then
				project=$(echo $line | cut -d' ' -f2)
				while read s_list;
				do
					if [[ $s_list != \#* ]];
					then
						p_project=$(echo $s_list | cut -d' ' -f3)
						if [[ $p_project == $project ]];
						then
							p_ip=$(echo $s_list | cut -d' ' -f1)
							p_comment=$(echo $s_list | cut -d' ' -f2)
							echo -e "${ORANGE}\t$p_ip \t${GREEN}": "$p_comment"
						fi
					fi
				done < ./serverlist.txt;
			fi
		fi
	done < ./projects.txt;
}

#-- Select and retrive servers login details from serverlist.txt
function selectserver {

	echo ""
	echo -e -n "${RED}Enter Server IP:${NC} " ; read _ip

	while read s_list;
	do
		if [[ $s_list != \#* ]];
		then
			ip=$(echo $s_list | cut -d' ' -f1)
			if [[ $ip == $_ip ]];
			then
				s_type=$(echo $s_list | cut -d' ' -f4)
				if [[ $s_type == "WIN"  &&  $ip == $_ip ]];
				then
					username=$(echo $s_list | cut -d' ' -f5)
					password=$(echo $s_list | cut -d' ' -f6)

				elif [[ $s_type == "LINUX"  &&  $ip == $_ip ]];
				then
					username=$(echo $s_list | cut -d' ' -f5)
					password=$(echo $s_list | cut -d' ' -f6)
					r_password=$(echo $s_list | cut -d' ' -f7)
					echo ""
					echo -e "${ORANGE}Username : ${YELLOW}$username"
					if [[ $password == ./bin/keys* ]];
					then
						echo -e "${ORANGE}Key File : ${YELLOW}$password"
					else
						echo -e "${ORANGE}Password : ${YELLOW}$password"
					fi
					echo -e "${ORANGE}Root     : ${RED}$r_password"
					echo ""
				fi
				return
			fi
		fi
	done < ./serverlist.txt;
}

#-- Server login (ssh/RDP) function
function logintoserver {

	if [[ $s_type == "LINUX" ]];
	then
		#---------
		if [[ $password == ./bin/keys/* ]];
		then
			sudo ssh -i $password $username@$ip
		elif [[ $password != ./bin/keys/* ]];
		then
			sshpass -p $password ssh -o StrictHostKeyChecking=no $username@$ip
		fi
	elif [[ $stype == "WIN" ]];
	then
		display_count=$(xrandr | grep "*" | wc -l)
		if [[ $display_count -eq 1 ]];
		then
        		rdesktop -0 -r disk:MYSHARE=/Drive_E/Share -r clipboard:PRIMARYCLIPBOARD -u $username -g 1365x710 -p $password $ip &> /dev/null &
		elif [[ $display_count -eq 2 ]];
		then
			resolution=$(xrandr | grep "*" | cut -d$'\n' -f2 | cut -d' ' -f4)
			w=$(echo $resolution | cut -d'x' -f1)
			h=$(echo $resolution | cut -d'x' -f2)
			h=`expr $h - 34`
			rdesktop -0 -r disk:MYSHARE=/Drive_E/Share -r clipboard:PRIMARYCLIPBOARD -u $username -g "$w"x"$h" -p $password $ip &> /dev/null &
		fi
	fi
}

#-- Program Body
printprojectlist
printserverlist
selectserver
logintoserver
exit 0
